#!/bin/bash
#
# Interactive installer for the moOde MQTT bridge.
#
# Run on the moOde Pi:   sudo ./install.sh
#
# Non-interactive use (skip the prompts by pre-setting the env vars):
#   sudo MQTT_HOST=192.168.1.200 TV_MAC=44:87:63:39:09:DE \
#        OUTPUT_DEVICE="CA CXA81 2.0" FIXED_VOLUME=yes ./install.sh
#
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BRIDGE_BIN="/usr/local/bin/moode-mqtt-bridge.sh"
BRIDGE_CONF="/etc/moode-mqtt-bridge.conf"
SERVICE="/etc/systemd/system/moode-mqtt-bridge.service"

log()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

MOODE_DB="/var/local/www/db/moode-sqlite3.db"
sqlget() { sqlite3 "$MOODE_DB" "SELECT value FROM $1 WHERE param='$2';" 2>/dev/null || true; }

[ "$(id -u)" -eq 0 ] || die "Run with sudo: sudo ./install.sh"
[ -f "$REPO_DIR/moode-mqtt-bridge.sh" ] || die "moode-mqtt-bridge.sh not found next to install.sh"

# --- collect settings ---------------------------------------------------
MQTT_HOST="${MQTT_HOST:-}"
TV_MAC="${TV_MAC:-}"
MQTT_PORT="${MQTT_PORT:-1883}"
APL_TIMEOUT="${APL_TIMEOUT:-}"
OUTPUT_DEVICE="${OUTPUT_DEVICE:-}"
FIXED_VOLUME="${FIXED_VOLUME:-}"

if [ -z "$MQTT_HOST" ]; then
  read -rp "MQTT broker host (LAN IP of the machine running Mosquitto/HA): " MQTT_HOST
fi
if [ -z "$TV_MAC" ]; then
  echo "Find the MAC on the Pi with:  bluetoothctl devices Paired"
  read -rp "TV/streaming-device Bluetooth MAC (e.g. 44:87:63:39:09:DE): " TV_MAC
fi
if [ -z "$APL_TIMEOUT" ]; then
  read -rp "AirPlay idle session timeout in seconds [1200]: " APL_TIMEOUT
  APL_TIMEOUT="${APL_TIMEOUT:-1200}"
fi

# Default the output device to whatever moOde currently has selected.
# Names with spaces are fine (e.g. "CA CXA81 2.0"); see `moodeutl --hwparams`.
_cur_dev="$(sqlget cfg_system adevname)"
_cur_card="$(sqlget cfg_system cardnum)"
if [ -z "$OUTPUT_DEVICE" ]; then
  read -rp "Audio output device name [${_cur_dev:-none}]: " OUTPUT_DEVICE
  OUTPUT_DEVICE="${OUTPUT_DEVICE:-$_cur_dev}"
fi
if [ -z "$FIXED_VOLUME" ]; then
  read -rp "Lock volume at 0dB (fixed, no volume control)? [Y/n]: " FIXED_VOLUME
  FIXED_VOLUME="${FIXED_VOLUME:-yes}"
fi
case "${FIXED_VOLUME,,}" in
  y|yes|1|true) FIXED_VOLUME=yes ;;
  *)            FIXED_VOLUME=no ;;
esac

# normalize + validate
TV_MAC="$(echo "$TV_MAC" | tr '[:lower:]' '[:upper:]')"
echo "$TV_MAC" | grep -Eq '^([0-9A-F]{2}:){5}[0-9A-F]{2}$' || die "Invalid MAC address: '$TV_MAC'"
[ -n "$MQTT_HOST" ] || die "MQTT host is required"
echo "$APL_TIMEOUT" | grep -Eq '^[0-9]+$' || die "AirPlay timeout must be a number"
[ -n "$OUTPUT_DEVICE" ] || die "Audio output device is required"

# Resolve the card number for the chosen device. The selected device's current
# card is reused when unchanged; otherwise match the ALSA short name from aplay.
CARDNUM=""
if [ -n "$_cur_dev" ] && [ "$OUTPUT_DEVICE" = "$_cur_dev" ] && [ -n "$_cur_card" ]; then
  CARDNUM="$_cur_card"
else
  CARDNUM="$(aplay -l 2>/dev/null | awk -v n="$OUTPUT_DEVICE" '
    match($0, /\[[^]]*\]/) {
      if (substr($0, RSTART + 1, RLENGTH - 2) == n) {
        if (match($0, /card [0-9]+/)) print substr($0, RSTART + 5, RLENGTH - 5)
        exit
      }
    }')"
fi

echo
log "MQTT host : $MQTT_HOST:$MQTT_PORT"
log "TV MAC    : $TV_MAC"
log "AirPlay idle timeout : ${APL_TIMEOUT}s"
log "Audio output : $OUTPUT_DEVICE${CARDNUM:+ (card $CARDNUM)}"
log "Fixed volume : $FIXED_VOLUME"
echo

# --- dependencies -------------------------------------------------------
log "Installing dependencies (mosquitto-clients, expect, sqlite3)"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq mosquitto-clients expect sqlite3 >/dev/null

# --- audio output device + fixed volume ---------------------------------
# moOde consumes /boot/moodecfg.ini and deletes it afterwards; `moodeutl -i`
# applies it now (a reboot finalizes it). This pins the DAC and volume mode
# without raw DB edits that a moOde software update could clobber.
MIXER_TYPE=$([ "$FIXED_VOLUME" = yes ] && echo none || echo software)
log "Configuring audio output: $OUTPUT_DEVICE (mixer: $MIXER_TYPE)"
{
  echo "; Generated by install.sh (moOde autoconfig)"
  echo "[Audio Device]"
  echo "adevname = \"$OUTPUT_DEVICE\""
  echo "mpdmixer = \"$MIXER_TYPE\""
  echo
  if [ -n "$CARDNUM" ]; then
    echo "[ALSA]"
    echo "cardnum = \"$CARDNUM\""
    echo
  fi
  echo "[MPD]"
  if [ -n "$CARDNUM" ]; then
    echo "device = \"$CARDNUM\""
  else
    warn "No card number found for '$OUTPUT_DEVICE'; moOde will resolve it by name at boot."
  fi
  echo "mixer_type = \"$MIXER_TYPE\""
} > /boot/moodecfg.ini

if moodeutl -i; then
  warn "Audio settings applied - reboot the Pi for them to take effect."
else
  warn "moodeutl -i reported an error; check the output above."
fi

# --- bridge script ------------------------------------------------------
log "Installing $BRIDGE_BIN"
install -m 755 "$REPO_DIR/moode-mqtt-bridge.sh" "$BRIDGE_BIN"

# --- config -------------------------------------------------------------
log "Writing $BRIDGE_CONF"
cat > "$BRIDGE_CONF" <<EOF
# moOde MQTT bridge configuration (generated by install.sh)
MQTT_HOST="$MQTT_HOST"
MQTT_PORT="$MQTT_PORT"
TV_MAC="$TV_MAC"
EOF
chmod 644 "$BRIDGE_CONF"

# --- systemd unit -------------------------------------------------------
log "Installing $SERVICE"
install -m 644 "$REPO_DIR/moode-mqtt-bridge.service" "$SERVICE"
systemctl daemon-reload
systemctl enable moode-mqtt-bridge >/dev/null 2>&1 || true
systemctl restart moode-mqtt-bridge

# --- AirPlay idle timeout ----------------------------------------------
if [ -f /etc/shairport-sync.conf ]; then
  log "Setting shairport-sync session_timeout = ${APL_TIMEOUT}"
  if grep -Eq '^[[:space:]]*session_timeout[[:space:]]*=' /etc/shairport-sync.conf; then
    sed -i "s|^[[:space:]]*session_timeout[[:space:]]*=.*|session_timeout = ${APL_TIMEOUT};|" /etc/shairport-sync.conf
  else
    warn "No 'session_timeout' line found in /etc/shairport-sync.conf."
    warn "Add 'session_timeout = ${APL_TIMEOUT};' inside the sessioncontrol { } block, then restart AirPlay."
  fi
  moodeutl -R --airplay 2>/dev/null || true
fi

# --- done ---------------------------------------------------------------
echo
log "Install complete."
echo "  Reboot : sudo reboot   # to apply the audio device / volume settings"
echo "  Status : systemctl status moode-mqtt-bridge --no-pager"
echo "  Logs   : journalctl -u moode-mqtt-bridge -f"
echo "  Config : $BRIDGE_CONF"
echo
echo "MQTT topics:"
echo "  state   moode/bluetooth/state  (connected | disconnected)"
echo "  state   moode/airplay/active   (on | off)"
echo "  command moode/cmd              (tv_on | tv_off | airplay_kick | airplay_on | airplay_off | bt_on | bt_off)"
