#!/bin/bash
#
# Interactive installer for the moOde MQTT bridge.
#
# Run on the moOde Pi:   sudo ./install.sh
#
# Non-interactive use (skip the prompts by pre-setting the env vars):
#   sudo MQTT_HOST=192.168.1.200 TV_MAC=44:87:63:39:09:DE ./install.sh
#
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BRIDGE_BIN="/usr/local/bin/moode-mqtt-bridge.sh"
BRIDGE_CONF="/etc/moode-mqtt-bridge.conf"
SERVICE="/etc/systemd/system/moode-mqtt-bridge.service"

log()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run with sudo: sudo ./install.sh"
[ -f "$REPO_DIR/moode-mqtt-bridge.sh" ] || die "moode-mqtt-bridge.sh not found next to install.sh"

# --- collect settings ---------------------------------------------------
MQTT_HOST="${MQTT_HOST:-}"
TV_MAC="${TV_MAC:-}"
MQTT_PORT="${MQTT_PORT:-1883}"
APL_TIMEOUT="${APL_TIMEOUT:-}"

if [ -z "$MQTT_HOST" ]; then
  read -rp "MQTT broker host (LAN IP of the machine running Mosquitto/HA): " MQTT_HOST
fi
if [ -z "$TV_MAC" ]; then
  echo "Find the MAC on the Pi with:  bluetoothctl devices Paired"
  read -rp "TV/streaming-device Bluetooth MAC (e.g. 44:87:63:39:09:DE): " TV_MAC
fi
if [ -z "$APL_TIMEOUT" ]; then
  read -rp "AirPlay idle session timeout in seconds [1200]: " APL_TIMEOUT
  APL_TIMEOUT="${APL_TIMEOUT:-1200}"
fi

# normalize + validate
TV_MAC="$(echo "$TV_MAC" | tr '[:lower:]' '[:upper:]')"
echo "$TV_MAC" | grep -Eq '^([0-9A-F]{2}:){5}[0-9A-F]{2}$' || die "Invalid MAC address: '$TV_MAC'"
[ -n "$MQTT_HOST" ] || die "MQTT host is required"
echo "$APL_TIMEOUT" | grep -Eq '^[0-9]+$' || die "AirPlay timeout must be a number"

echo
log "MQTT host : $MQTT_HOST:$MQTT_PORT"
log "TV MAC    : $TV_MAC"
log "AirPlay idle timeout : ${APL_TIMEOUT}s"
echo

# --- dependencies -------------------------------------------------------
log "Installing dependencies (mosquitto-clients, expect, sqlite3)"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq mosquitto-clients expect sqlite3 >/dev/null

# --- bridge script ------------------------------------------------------
log "Installing $BRIDGE_BIN"
install -m 755 "$REPO_DIR/moode-mqtt-bridge.sh" "$BRIDGE_BIN"

# --- config -------------------------------------------------------------
log "Writing $BRIDGE_CONF"
cat > "$BRIDGE_CONF" <<EOF
# moOde MQTT bridge configuration (generated by install.sh)
MQTT_HOST="$MQTT_HOST"
MQTT_PORT="$MQTT_PORT"
TV_MAC="$TV_MAC"
EOF
chmod 644 "$BRIDGE_CONF"

# --- systemd unit -------------------------------------------------------
log "Installing $SERVICE"
install -m 644 "$REPO_DIR/moode-mqtt-bridge.service" "$SERVICE"
systemctl daemon-reload
systemctl enable moode-mqtt-bridge >/dev/null 2>&1 || true
systemctl restart moode-mqtt-bridge

# --- AirPlay idle timeout ----------------------------------------------
if [ -f /etc/shairport-sync.conf ]; then
  log "Setting shairport-sync session_timeout = ${APL_TIMEOUT}"
  if grep -Eq '^[[:space:]]*session_timeout[[:space:]]*=' /etc/shairport-sync.conf; then
    sed -i "s|^[[:space:]]*session_timeout[[:space:]]*=.*|session_timeout = ${APL_TIMEOUT};|" /etc/shairport-sync.conf
  else
    warn "No 'session_timeout' line found in /etc/shairport-sync.conf."
    warn "Add 'session_timeout = ${APL_TIMEOUT};' inside the sessioncontrol { } block, then restart AirPlay."
  fi
  moodeutl -R --airplay 2>/dev/null || true
fi

# --- done ---------------------------------------------------------------
echo
log "Install complete."
echo "  Status : systemctl status moode-mqtt-bridge --no-pager"
echo "  Logs   : journalctl -u moode-mqtt-bridge -f"
echo "  Config : $BRIDGE_CONF"
echo
echo "MQTT topics:"
echo "  state   moode/bluetooth/state  (connected | disconnected)"
echo "  state   moode/airplay/active   (on | off)"
echo "  command moode/cmd              (tv_on | tv_off | airplay_kick | airplay_on | airplay_off | bt_on | bt_off)"
